services:
  api:
    command: sh -c "npm install @aws-sdk/client-s3 @aws-sdk/client-textract @aws-sdk/client-comprehend @aws-sdk/client-bedrock-runtime @langchain/aws@^0.1.15 && node /app/langchain-aws-citation-patch-v4.js && npm run backend"
    
    # Optimizaciones de rendimiento para streaming
    environment:
      # Aumentar memoria disponible para Node.js (4GB)
      - NODE_OPTIONS=--max-old-space-size=4096
      # Aumentar pool de threads para operaciones asíncronas
      - UV_THREADPOOL_SIZE=128
      # Desactivar límites de listeners de eventos
      - NODE_NO_WARNINGS=1

    volumes:
      # Configuración LibreChat
      - ./librechat.yaml:/app/librechat.yaml

      # Archivos API personalizados
      - ./api/app/clients/tools/util/fileSearch.js:/app/api/app/clients/tools/util/fileSearch.js
      - ./api/server/services/Files/process.js:/app/api/server/services/Files/process.js
      - ./api/server/services/Files/Local/crud.js:/app/api/server/services/Files/Local/crud.js
      - ./api/server/services/Files/Firebase/crud.js:/app/api/server/services/Files/Firebase/crud.js
      - ./api/server/controllers/agents/client.js:/app/api/server/controllers/agents/client.js
      - ./api/server/controllers/agents/request.js:/app/api/server/controllers/agents/request.js
      - ./api/app/clients/prompts/titlePrompts.js:/app/api/app/clients/prompts/titlePrompts.js
      
      # Default Model Configuration
      - ./api/server/services/AppService.js:/app/api/server/services/AppService.js
      - ./api/server/routes/config.js:/app/api/server/routes/config.js
      - ./packages/data-provider/src/config.ts:/app/packages/data-provider/src/config.ts
      - ./packages/data-provider/src/file-config.ts:/app/packages/data-provider/src/file-config.ts
      - ./packages/api/src/app/interface.ts:/app/packages/api/src/app/interface.ts
      - ./client/src/utils/endpoints.ts:/app/client/src/utils/endpoints.ts
      - ./client/src/utils/files.ts:/app/client/src/utils/files.ts
      - ./client/src/hooks/Files/useFileHandling.ts:/app/client/src/hooks/Files/useFileHandling.ts
      - ./client/src/components/SidePanel/Agents/FileContext.tsx:/app/client/src/components/SidePanel/Agents/FileContext.tsx
      - ./client/src/components/SidePanel/Agents/FileSearch.tsx:/app/client/src/components/SidePanel/Agents/FileSearch.tsx
      - ./client/src/components/SidePanel/Agents/Code/Files.tsx:/app/client/src/components/SidePanel/Agents/Code/Files.tsx
      - ./client/src/hooks/Input/useSelectMention.ts:/app/client/src/hooks/Input/useSelectMention.ts
      
      # Sidebar Navigation Width Configuration
      - ./client/src/components/Nav/Nav.tsx:/app/client/src/components/Nav/Nav.tsx
      - ./client/src/components/Nav/ResizableNavGroup.tsx:/app/client/src/components/Nav/ResizableNavGroup.tsx
      
      # Right SidePanel Configuration
      - ./client/src/components/SidePanel/SidePanel.tsx:/app/client/src/components/SidePanel/SidePanel.tsx
      - ./client/src/components/SidePanel/SidePanelGroup.tsx:/app/client/src/components/SidePanel/SidePanelGroup.tsx
      
      # Interface Features Configuration (multiConvo, temporaryChat, modularChat)
      - ./client/src/components/Chat/Header.tsx:/app/client/src/components/Chat/Header.tsx
      - ./client/src/hooks/Input/useQueryParams.ts:/app/client/src/hooks/Input/useQueryParams.ts
      - ./client/src/hooks/Conversations/usePresets.ts:/app/client/src/hooks/Conversations/usePresets.ts
      - ./client/src/components/Chat/Menus/Endpoints/ModelSelectorContext.tsx:/app/client/src/components/Chat/Menus/Endpoints/ModelSelectorContext.tsx
      
      # Upload Text Labels and Language Configuration
      # Traducciones en español completas: 1279 claves (agregadas 527 traducciones faltantes)
      # LibreChat reemplazado por Transbank en todas las referencias
      - ./client/src/locales/es/translation.json:/app/client/src/locales/es/translation.json
      - ./client/src/locales/i18n.ts:/app/client/src/locales/i18n.ts
      - ./client/src/store/language.ts:/app/client/src/store/language.ts
      
      # Theme Configuration (Force Light Theme)
      - ./packages/client/src/theme/atoms/themeAtoms.ts:/app/packages/client/src/theme/atoms/themeAtoms.ts
      - ./packages/client/src/theme/context/ThemeProvider.tsx:/app/packages/client/src/theme/context/ThemeProvider.tsx
      - ./client/src/App.jsx:/app/client/src/App.jsx
      
      # Disable Features Configuration (Speech, Language Selector, Message Editing)
      - ./client/src/store/settings.ts:/app/client/src/store/settings.ts
      - ./client/src/components/Nav/SettingsTabs/General/General.tsx:/app/client/src/components/Nav/SettingsTabs/General/General.tsx
      - ./client/src/hooks/useGenerationsByLatest.ts:/app/client/src/hooks/useGenerationsByLatest.ts
      - ./client/src/components/Nav/SettingsTabs/Speech/STT/SpeechToTextSwitch.tsx:/app/client/src/components/Nav/SettingsTabs/Speech/STT/SpeechToTextSwitch.tsx
      - ./client/src/components/Nav/SettingsTabs/Speech/TTS/TextToSpeechSwitch.tsx:/app/client/src/components/Nav/SettingsTabs/Speech/TTS/TextToSpeechSwitch.tsx
      - ./client/src/components/Chat/Messages/HoverButtons.tsx:/app/client/src/components/Chat/Messages/HoverButtons.tsx
      
      # Módulo de administración de conversaciones - Backend
      - ./api/server/routes/admin/conversations.js:/app/api/server/routes/admin/conversations.js
      - ./api/server/routes/index.js:/app/api/server/routes/index.js
      - ./api/server/index.js:/app/api/server/index.js
      - ./api/server/middleware/roles/admin.js:/app/api/server/middleware/roles/admin.js
      - ./api/server/middleware/requireJwtAuth.js:/app/api/server/middleware/requireJwtAuth.js
      
      # Módulo de administración de conversaciones - Frontend
      - ./client/src/components/Admin/AdminConversations.tsx:/app/client/src/components/Admin/AdminConversations.tsx
      - ./client/src/components/Admin/AdminConversationsFilters.tsx:/app/client/src/components/Admin/AdminConversationsFilters.tsx
      - ./client/src/components/Admin/AdminConversationsGrid.tsx:/app/client/src/components/Admin/AdminConversationsGrid.tsx
      - ./client/src/components/Admin/AdminConversationDetail.tsx:/app/client/src/components/Admin/AdminConversationDetail.tsx
      - ./client/src/components/Nav/AdminConversationsButton.tsx:/app/client/src/components/Nav/AdminConversationsButton.tsx
      
      # Sidebar redimensionable - Frontend
      - ./client/src/components/Nav/Nav.tsx:/app/client/src/components/Nav/Nav.tsx
      - ./client/src/components/Nav/ResizableNavGroup.tsx:/app/client/src/components/Nav/ResizableNavGroup.tsx
      - ./client/src/components/Nav/index.ts:/app/client/src/components/Nav/index.ts
      - ./client/src/components/Conversations/Conversations.tsx:/app/client/src/components/Conversations/Conversations.tsx
      - ./client/src/routes/Root.tsx:/app/client/src/routes/Root.tsx
      - ./client/src/routes/index.tsx:/app/client/src/routes/index.tsx
      
      # Localizaciones
      - ./client/src/localization/admin-translations.json:/app/client/src/localization/admin-translations.json
      
      # Nova Canvas - Generación de imágenes con Bedrock
      - ./api/app/clients/tools/structured/NovaCanvas.js:/app/api/app/clients/tools/structured/NovaCanvas.js
      - ./api/app/clients/tools/util/handleTools.js:/app/api/app/clients/tools/util/handleTools.js
      - ./api/app/clients/tools/index.js:/app/api/app/clients/tools/index.js
      - ./api/app/clients/tools/manifest.json:/app/api/app/clients/tools/manifest.json
      - ./api/package.json:/app/api/package.json
      - ./packages/api/src/utils/tokens.ts:/app/packages/api/src/utils/tokens.ts
      - ./packages/data-provider/src/config.ts:/app/packages/data-provider/src/config.ts
      - ./librechat.yaml:/app/librechat.yaml

    # Optimizaciones de Streaming
      - ./api/app/clients/TextStream.js:/app/api/app/clients/TextStream.js
      - ./api/server/middleware/setHeaders.js:/app/api/server/middleware/setHeaders.js
      - ./api/server/services/AssistantService.js:/app/api/server/services/AssistantService.js
      - ./client/src/components/Chat/Messages/Content/MessageContent.tsx:/app/client/src/components/Chat/Messages/Content/MessageContent.tsx
      - ./client/src/components/Chat/Messages/Content/SearchContent.tsx:/app/client/src/components/Chat/Messages/Content/SearchContent.tsx

      # Bedrock Citations Support - Backend
      - ./api/server/services/Endpoints/bedrock/initialize.js:/app/api/server/services/Endpoints/bedrock/initialize.js
      - ./packages/data-provider/src/types/runs.ts:/app/packages/data-provider/src/types/runs.ts
      - ./packages/data-provider/src/types/assistants.ts:/app/packages/data-provider/src/types/assistants.ts
      - ./api/server/controllers/agents/callbacks.js:/app/api/server/controllers/agents/callbacks.js
      - ./api/server/controllers/agents/request.js:/app/api/server/controllers/agents/request.js
      
      # Bedrock Citations Support - Frontend
      - ./client/src/components/Chat/Messages/Content/Parts/Citation.tsx:/app/client/src/components/Chat/Messages/Content/Parts/Citation.tsx
      - ./client/src/components/Chat/Messages/Content/Part.tsx:/app/client/src/components/Chat/Messages/Content/Part.tsx
      
      # LangChain AWS Citation Patch V3
      - ./langchain-aws-citation-patch-v4.js:/app/langchain-aws-citation-patch-v4.js
      
      # Sistema Soft Delete - Esquemas de Base de Datos
      - ./packages/data-schemas/src/schema/convo.ts:/app/packages/data-schemas/src/schema/convo.ts
      - ./packages/data-schemas/src/schema/file.ts:/app/packages/data-schemas/src/schema/file.ts
      - ./packages/data-schemas/src/schema/message.ts:/app/packages/data-schemas/src/schema/message.ts
      - ./packages/data-schemas/src/types/convo.ts:/app/packages/data-schemas/src/types/convo.ts
      - ./packages/data-schemas/src/types/file.ts:/app/packages/data-schemas/src/types/file.ts
      - ./packages/data-schemas/src/types/message.ts:/app/packages/data-schemas/src/types/message.ts
      
      # Sistema Soft Delete - Modelos y Rutas Backend
      - ./api/models/Conversation.js:/app/api/models/Conversation.js
      - ./api/models/File.js:/app/api/models/File.js
      - ./api/models/Message.js:/app/api/models/Message.js
      - ./api/models/index.js:/app/api/models/index.js
      - ./api/server/routes/convos.js:/app/api/server/routes/convos.js



  rag_api:
    volumes:
      - ./rag_api/hybrid_search/models.py:/app/app/models.py
      - ./rag_api/hybrid_search/document_routes.py:/app/app/routes/document_routes.py
      - ./rag_api/hybrid_search/hybrid_search.py:/app/app/services/hybrid_search.py
      - ./rag_api/hybrid_search/config.py:/app/app/config.py
      - ./rag_api/hybrid_search/async_pg_vector.py:/app/app/services/vector_store/async_pg_vector.py
    ports:
      - "3333:8000"

  vectordb:
    ports:
      - "5433:5432"

  mongodb:
    ports:
      - "27017:27017"
